PUT http://localhost:3000/tasks/2
Content-Type: application/json

{
  "name": "",
  "status": "To do",
  "due_date": "2024-02-14"
}

###
DELETE http://localhost:3000/tasks/4

###
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "name": "",
  "status": "To Do",
  "due_date": "2024-02-14"
}

###

GET http://localhost:3000/tasks?sort=name&filter=Ready

###

GET http://localhost:3000/tasks?filter=Ready

###

GET http://localhost:3000/tasks?sort=name

###

GET http://localhost:3000/tasks

###
